apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "java-demo-chart.fullname" . }}-rbac
rules:
  - apiGroups: [""]
    resources: ["services", "pods"]   # add other resources if needed
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
