apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "java-demo-chart.fullname" . }}-rbac-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "java-demo-chart.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "java-demo-chart.fullname" . }}-rbac
  apiGroup: rbac.authorization.k8s.io
